### ISSUE TITLE
UnitOfMeasure - Introduce Drop-Down Component

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/isodata#19]
Introduce - similar to Currency, ... - a ui component for usage in other services.
Please introduce an option to change between a short or a longer (that includes the name) variant.

**Comment by kwierchris** [comment]
As stated before, we need a new **UI component** in order to display **Unit of Measure** data. This component should be similar to the other components we have for countries, currencies and languages.

Unit of Measure has a name, a short name and a symbol property. Create an input option for the component so it can switch it's output and the displayed data.

Further information about how the data looks like and how to get it is available [here](https://github.com/OpusCapita/isodata/wiki/UnitOfMeasure.endpoint) and [here](https://github.com/OpusCapita/isodata/wiki/unitOfMeasure.model). The current components are located in [this directory](https://github.com/OpusCapita/isodata/tree/develop/src/client/components).
